### ISSUE TITLE
Idea: White theme for WWDC 2021?

### ISSUE THREAD

**Issue by lhnguyens** [runys/WWDC-Xcode-Themes#1]
Sorry but not sorry? :D 

If you can, it would be useful to have white theme for them sunnier days

**Comment by runys** [comment]
Sure, don't be sorry! Do you think it could look like the code they presented in the opening Keynote?

**Comment by lhnguyens** [comment]
Yes, for sure :D Thanks man!

**Comment by runys** [comment]
I've just checked the Platforms State of the Union video and the light theme they use there to show code is the Presentation Light theme from Xcode. So no need to create a new one. Do you have any other ideas?

**Comment by lhnguyens** [comment]
Ah okay, thanks for finding it out anyway :D
